[package]
name = "nostr-minions"
version = "0.1.16"
edition = "2021"
license = "BSD-3-Clause"
description = "A Yew-based framework for client side Nostr apps"
repository = "https://github.com/illuminodes/minions"
readme = "README.md"
homepage = "https://github.com/illuminodes/minions"

[features]
default = []
ag-grid = []
bitcoin-qr = []
full-calendar = ["toastify"]
leaflet = []
toastify = []
uploads = []
all-widgets = ["ag-grid", "bitcoin-qr", "full-calendar", "leaflet", "toastify", "uploads"]

[dependencies]
# Nostr Stack


# nostro2 = "0.3.5"
nostro2 =  { path = "../NostrO2/nostro2" }
# nostro2-signer =  "0.1.8"
nostro2-signer =  { path = "../NostrO2/nostro2-signer" }
# nostro2-web-signer =  "0.1.0"
# nostro2-web-signer =  { path = "../NostrO2/nostro2-web-signer" }
upload-things = "0.1.2"
lucide-yew = "1.1.0"
uuid = { version = "1.15", features = ["v4", "js"] }

# JSON manipulation
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6.5"

# DOM and Browser Bindings
gloo = "0.11"
web-sys = { version = "0.3", features = [ "Window", "Clipboard",  "Navigator",
"SubtleCrypto", "CryptoKey",  "Crypto", "AesKeyGenParams", "AesGcmParams", 
"IdbFactory", "IdbOpenDbOptions", "IdbObjectStoreParameters","IdbOpenDbRequest", "IdbTransaction", 
"IdbRequest", "IdbDatabase", "IdbObjectStore", "IdbRequestReadyState", "IdbTransactionMode", 
"Geolocation", "Response", "ReadableStream",  "DomStringList",
"ServiceWorkerContainer", "ServiceWorkerGlobalScope", "FetchEvent"] }

tokio = { version = "1", features = ["macros", "sync"] }
wasm-bindgen-futures = "0.4"

# PWA stack
yew = { version = "0.21.0" }
yew-router = "0.18.0"
wasm-bindgen = "0.2"

[dev-dependencies]
gloo-timers = "0.3.0"
wasm-bindgen-test = "0.3"
yew = { version = "0.21.0",  features = ["csr"] }
