[package]
name = "nostr-minions"
version = "0.3.1"
edition = "2021"
license = "BSD-3-Clause"
description = "A Yew-based framework for client side Nostr apps"
repository = "https://github.com/illuminodes/minions"
readme = "README.md"
homepage = "https://github.com/illuminodes/minions"

[features]
test-components = []

[dependencies]
# Nostr Stack
nostro2 = "0.4.2"
nostro2-signer = "0.2.2"
# nostro2 = { path = "../NostrO2/nostro2" }
# nostro2-signer = { path = "../NostrO2/nostro2-signer" }

# JSON manipulation
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6.5"

# DOM and Browser Bindings
web-sys = { version = "0.3", features = [
    "SubtleCrypto", "CryptoKey", "Window", "Crypto",
    "AesKeyGenParams", "AesGcmParams", "DomStringList",
] }

# I/O
wasm-bindgen-futures = "0.4"

# PWA stack
yew = { version = "0.21.0" }
wasm-bindgen = "0.2"
idb = "0.6.4"

