[package]
name = "test_app"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-timers = "0.3.0"
wasm-bindgen-test = "0.3"
yew = { version = "0.21.0",  features = ["csr"] }
nostr-minions = { path = "../" }
yew-full-calendar = { path = "../../yew-full-calendar" }
web-sys = "0.3.82"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
